server:
  port: 8190

spring:
  application:
    name: persistence_project
  datasource:
    url: jdbc:mysql://localhost:3306/persistence_project?allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
    username: "root"
    password: "Manyamane@21"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true